#!/bin/sh
# Flexible NFS server setup on FreeBSD
# Usage: ./setup_nfs_server.sh /export/dir client1_IP client2_IP ...

EXPORT_DIR=${1:-/tmp}
shift
CLIENTS="$@"

if [ -z "${CLIENTS}" ]; then
    echo "Usage: $0 EXPORT_DIR client1_IP [client2_IP ...]"
    exit 1
fi

echo ">>> Setting up NFS export: ${EXPORT_DIR} for clients: ${CLIENTS}"

# Ensure export directory exists
mkdir -p ${EXPORT_DIR}

# Build /etc/exports entry
EXPORTS_LINE="${EXPORT_DIR} -maproot=root -network ${CLIENTS}"

# Write /etc/exports (overwrite for simplicity)
{
    echo "# Auto-generated by setup_nfs_server.sh"
    echo "V4: /"
    printf "%s " "${EXPORT_DIR}" "-maproot=root"
    for c in ${CLIENTS}; do
        printf " %s" "${c}"
    done
    echo
} > /etc/exports

echo ">>> New /etc/exports:"
cat /etc/exports

# Enable NFS services in rc.conf (if not already)
sysrc nfs_server_enable=YES
sysrc mountd_enable=YES
sysrc rpcbind_enable=YES

# Restart services
service rpcbind restart
service mountd restart
service nfsd restart

echo ">>> NFS server ready. Exports:"
showmount -e